<?php

namespace Database\Seeders;

use App\Models\Stat;
use Illuminate\Database\Seeder;

class StatSeeder extends Seeder
{
    public function run(): void
    {
        foreach ([
            [
                'group' => 'home_hero',
                'label' => 'Media managed',
                'value' => 225.0,
                'prefix' => '$',
                'suffix' => 'M',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 1,
            ],
            [
                'group' => 'home_hero',
                'label' => 'Revenue generated',
                'value' => 750.0,
                'prefix' => '$',
                'suffix' => 'M+',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 2,
            ],
            [
                'group' => 'home_hero',
                'label' => 'Billion-dollar clients',
                'value' => 7.0,
                'prefix' => '',
                'suffix' => '',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 3,
            ],
            [
                'group' => 'home_hero',
                'label' => 'Brands scaled',
                'value' => 40.0,
                'prefix' => '',
                'suffix' => '+',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 4,
            ],
            [
                'group' => 'pedigree',
                'label' => 'Media managed',
                'value' => 225.0,
                'prefix' => '$',
                'suffix' => 'M',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 1,
            ],
            [
                'group' => 'pedigree',
                'label' => 'Revenue generated',
                'value' => 750.0,
                'prefix' => '$',
                'suffix' => 'M+',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 2,
            ],
            [
                'group' => 'pedigree',
                'label' => 'Billion-dollar brand clients',
                'value' => 7.0,
                'prefix' => '',
                'suffix' => '',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 3,
            ],
            [
                'group' => 'pedigree',
                'label' => 'Combined years at mega brands',
                'value' => 100.0,
                'prefix' => '',
                'suffix' => '+',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 4,
            ],
            [
                'group' => 'pedigree',
                'label' => 'Brands scaled',
                'value' => 40.0,
                'prefix' => '',
                'suffix' => '+',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 5,
            ],
            [
                'group' => 'pedigree',
                'label' => 'Outperformed client\'s prior team',
                'value' => 100.0,
                'prefix' => '',
                'suffix' => '%',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 6,
            ],
            [
                'group' => 'engine_hero',
                'label' => 'Point audit in Review',
                'value' => 13.0,
                'prefix' => '',
                'suffix' => '',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 1,
            ],
            [
                'group' => 'engine_hero',
                'label' => 'Media run through the Engine',
                'value' => 225.0,
                'prefix' => '$',
                'suffix' => 'M',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 2,
            ],
            [
                'group' => 'engine_hero',
                'label' => 'Years undefeated',
                'value' => 8.0,
                'prefix' => '',
                'suffix' => '',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 3,
            ],
            [
                'group' => 'engine_hero',
                'label' => 'Pitches, zero losses',
                'value' => 19.0,
                'prefix' => '',
                'suffix' => '',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 4,
            ],
            [
                'group' => 'team_hero',
                'label' => 'Combined years at mega brands',
                'value' => 100.0,
                'prefix' => '',
                'suffix' => '+',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 1,
            ],
            [
                'group' => 'team_hero',
                'label' => 'Brands scaled',
                'value' => 40.0,
                'prefix' => '',
                'suffix' => '+',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 2,
            ],
            [
                'group' => 'team_hero',
                'label' => 'Billion-dollar clients',
                'value' => 7.0,
                'prefix' => '',
                'suffix' => '',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 3,
            ],
            [
                'group' => 'contact_hero',
                'label' => 'Offices, one team',
                'value' => 5.0,
                'prefix' => '',
                'suffix' => '',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 2,
            ],
            [
                'group' => 'engine_proof',
                'label' => 'Monthly budget scaled',
                'value' => 7.5,
                'prefix' => '',
                'suffix' => 'x',
                'decimals' => 1,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 1,
            ],
            [
                'group' => 'engine_proof',
                'label' => 'ROAS lift in 4 months',
                'value' => 40.0,
                'prefix' => '+',
                'suffix' => '%',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 2,
            ],
            [
                'group' => 'engine_proof',
                'label' => 'To 3x ROAS for one client',
                'value' => 45.0,
                'prefix' => '',
                'suffix' => ' days',
                'decimals' => 0,
                'is_static' => false,
                'static_value' => null,
                'sort_order' => 3,
            ],
            [
                'group' => 'contact_hero',
                'label' => 'Access to your team',
                'value' => null,
                'prefix' => '',
                'suffix' => '',
                'decimals' => 0,
                'is_static' => true,
                'static_value' => '24/7',
                'sort_order' => 1,
            ],
        ] as $row) {
            Stat::create($row);
        }
    }
}
